/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IphoneRouteImport } from './routes/iphone'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IphoneIndexRouteImport } from './routes/iphone.index'
import { Route as IphoneModelRouteImport } from './routes/iphone.$model'

const IphoneRoute = IphoneRouteImport.update({
  id: '/iphone',
  path: '/iphone',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IphoneIndexRoute = IphoneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IphoneRoute,
} as any)
const IphoneModelRoute = IphoneModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => IphoneRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iphone': typeof IphoneRouteWithChildren
  '/iphone/$model': typeof IphoneModelRoute
  '/iphone/': typeof IphoneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iphone/$model': typeof IphoneModelRoute
  '/iphone': typeof IphoneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iphone': typeof IphoneRouteWithChildren
  '/iphone/$model': typeof IphoneModelRoute
  '/iphone/': typeof IphoneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/iphone' | '/iphone/$model' | '/iphone/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/iphone/$model' | '/iphone'
  id: '__root__' | '/' | '/iphone' | '/iphone/$model' | '/iphone/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IphoneRoute: typeof IphoneRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iphone': {
      id: '/iphone'
      path: '/iphone'
      fullPath: '/iphone'
      preLoaderRoute: typeof IphoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iphone/': {
      id: '/iphone/'
      path: '/'
      fullPath: '/iphone/'
      preLoaderRoute: typeof IphoneIndexRouteImport
      parentRoute: typeof IphoneRoute
    }
    '/iphone/$model': {
      id: '/iphone/$model'
      path: '/$model'
      fullPath: '/iphone/$model'
      preLoaderRoute: typeof IphoneModelRouteImport
      parentRoute: typeof IphoneRoute
    }
  }
}

interface IphoneRouteChildren {
  IphoneModelRoute: typeof IphoneModelRoute
  IphoneIndexRoute: typeof IphoneIndexRoute
}

const IphoneRouteChildren: IphoneRouteChildren = {
  IphoneModelRoute: IphoneModelRoute,
  IphoneIndexRoute: IphoneIndexRoute,
}

const IphoneRouteWithChildren =
  IphoneRoute._addFileChildren(IphoneRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IphoneRoute: IphoneRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
